/**
 * Historical ocean liners — distinct proportions, not reskins.
 * Dimensions are stylized but relatively scaled (length units ≈ meters / 10).
 * Compartments run bow → stern (index 0 = bow).
 * Hull color = topside; antifoul red is applied below the waterline in the mesh.
 * Optional livery: sheerLine (thin line under the deck edge), bootTop (band at
 * the waterline), hospital (green band + red crosses), funnelBands (black
 * whistle bands, as fraction of funnel height), funnelBandColors (stripes
 * under the black top), dummyFunnels (indices that never smoked).
 */

export const SHIPS = [
  {
    id: "titanic",
    name: "RMS Titanic",
    year: 1912,
    length: 26.9,
    beam: 2.85,
    height: 2.65,
    draft: 1.05,
    funnels: 4,
    funnelColor: 0xc8913f,
    dummyFunnels: [3],
    hullColor: 0x14161a,
    sheerLine: 0xc9a23a,
    superstructureColor: 0xf0ebe3,
    compartments: 6,
    notes: "Olympic-class — long, four buff funnels (the fourth a dummy)",
  },
  {
    id: "britannic",
    name: "HMHS Britannic",
    year: 1914,
    length: 27.2,
    beam: 2.95,
    height: 2.75,
    draft: 1.08,
    funnels: 4,
    funnelColor: 0xc8913f,
    dummyFunnels: [3],
    hullColor: 0xefebe3,
    hospital: { band: 0x2f7a3c, cross: 0xb8232a },
    superstructureColor: 0xf4efe8,
    compartments: 6,
    notes: "Olympic sister in hospital-ship white, green band and red crosses",
  },
  {
    id: "nomadic",
    name: "SS Nomadic",
    year: 1911,
    length: 6.7,
    beam: 1.45,
    height: 1.55,
    draft: 0.52,
    funnels: 1,
    funnelColor: 0xc8913f,
    hullColor: 0x15171b,
    sheerLine: 0xc9a23a,
    superstructureColor: 0xf7f2ea,
    compartments: 3,
    notes: "Titanic's tender — compact ferry hull",
  },
  {
    id: "queen-elizabeth",
    name: "RMS Queen Elizabeth",
    year: 1940,
    length: 31.4,
    beam: 3.65,
    height: 3.25,
    draft: 1.22,
    funnels: 2,
    funnelColor: 0xc0461f,
    funnelBands: [0.62, 0.72],
    hullColor: 0x111317,
    bootTop: 0xe8e4dc,
    superstructureColor: 0xf8f4ed,
    compartments: 7,
    notes: "Cunard giant — beamy, two tall red funnels",
  },
  {
    id: "lusitania",
    name: "RMS Lusitania",
    year: 1906,
    length: 24.0,
    beam: 2.72,
    height: 2.55,
    draft: 1.0,
    funnels: 4,
    funnelColor: 0xc0461f,
    funnelBands: [0.58, 0.7],
    hullColor: 0x131519,
    superstructureColor: 0xf0eae2,
    compartments: 5,
    notes: "Four-funnel Cunarder, fine bow",
  },
  {
    id: "andrea-doria",
    name: "SS Andrea Doria",
    year: 1951,
    length: 21.3,
    beam: 2.8,
    height: 2.85,
    draft: 0.95,
    funnels: 1,
    funnelColor: 0xf0ebe2,
    funnelBandColors: [0x2f7a3c, 0xf0ebe2, 0xb8232a],
    hullColor: 0x121418,
    bootTop: 0xe8e4dc,
    superstructureColor: 0xfaf6f0,
    compartments: 5,
    notes: "Post-war Italian liner — sleek, single funnel",
  },
  {
    id: "empress",
    name: "RMS Empress of Ireland",
    year: 1906,
    length: 17.4,
    beam: 2.25,
    height: 2.25,
    draft: 0.88,
    funnels: 2,
    funnelColor: 0xcfa24a,
    hullColor: 0x14161a,
    superstructureColor: 0xeee8e0,
    compartments: 4,
    notes: "Canadian Pacific — shorter, two funnels",
  },
];

export function getShip(id) {
  return SHIPS.find((s) => s.id === id) ?? SHIPS[0];
}
