/**
 * Historical ocean liners — distinct proportions, not reskins.
 * Dimensions are stylized but relatively scaled (length units ≈ meters / 10).
 * Compartments run bow → stern (index 0 = bow).
 * Hull color = topside; antifoul red is applied below the waterline in the mesh.
 */

export const SHIPS = [
  {
    id: "titanic",
    name: "RMS Titanic",
    year: 1912,
    length: 26.9,
    beam: 2.85,
    height: 2.65,
    draft: 1.05,
    funnels: 4,
    funnelColor: 0xc45c26,
    hullColor: 0x12161f,
    superstructureColor: 0xf0ebe3,
    compartments: 6,
    notes: "Olympic-class — long, four buff funnels",
  },
  {
    id: "britannic",
    name: "HMHS Britannic",
    year: 1914,
    length: 27.2,
    beam: 2.95,
    height: 2.75,
    draft: 1.08,
    funnels: 4,
    funnelColor: 0xc45c26,
    hullColor: 0x141a26,
    superstructureColor: 0xf4efe8,
    compartments: 6,
    notes: "Slightly larger Olympic sister",
  },
  {
    id: "nomadic",
    name: "SS Nomadic",
    year: 1911,
    length: 6.7,
    beam: 1.45,
    height: 1.55,
    draft: 0.52,
    funnels: 1,
    funnelColor: 0x2c5282,
    hullColor: 0x151c28,
    superstructureColor: 0xf7f2ea,
    compartments: 3,
    notes: "Titanic's tender — compact ferry hull",
  },
  {
    id: "queen-elizabeth",
    name: "RMS Queen Elizabeth",
    year: 1940,
    length: 31.4,
    beam: 3.65,
    height: 3.25,
    draft: 1.22,
    funnels: 2,
    funnelColor: 0xc53030,
    hullColor: 0x0c121c,
    superstructureColor: 0xf8f4ed,
    compartments: 7,
    notes: "Cunard giant — beamy, two tall red funnels",
  },
  {
    id: "lusitania",
    name: "RMS Lusitania",
    year: 1906,
    length: 24.0,
    beam: 2.72,
    height: 2.55,
    draft: 1.0,
    funnels: 4,
    funnelColor: 0xb83280,
    hullColor: 0x141a24,
    superstructureColor: 0xf0eae2,
    compartments: 5,
    notes: "Four-funnel Cunarder, fine bow",
  },
  {
    id: "andrea-doria",
    name: "SS Andrea Doria",
    year: 1951,
    length: 21.3,
    beam: 2.8,
    height: 2.85,
    draft: 0.95,
    funnels: 1,
    funnelColor: 0x2b6cb0,
    hullColor: 0x101828,
    superstructureColor: 0xfaf6f0,
    compartments: 5,
    notes: "Post-war Italian liner — sleek, single funnel",
  },
  {
    id: "empress",
    name: "RMS Empress of Ireland",
    year: 1906,
    length: 17.4,
    beam: 2.25,
    height: 2.25,
    draft: 0.88,
    funnels: 2,
    funnelColor: 0x2f855a,
    hullColor: 0x131820,
    superstructureColor: 0xeee8e0,
    compartments: 4,
    notes: "Canadian Pacific — shorter, two funnels",
  },
];

export function getShip(id) {
  return SHIPS.find((s) => s.id === id) ?? SHIPS[0];
}
