/**
 * Historical ocean liners and WWII warships — distinct proportions, not reskins.
 * Dimensions are stylized but relatively scaled (length units ≈ meters / 10).
 * `height` sets the silhouette scale; the main deck sits at 0.285 × height.
 * Compartments run bow → stern (index 0 = bow).
 * category: liner | battleship | cruiser | destroyer | carrier | submarine.
 * navy groups warships in the ship picker (see NAVIES).
 * Hull color = topside; antifoul red is applied below the waterline in the mesh.
 * Optional livery: sheerLine (thin line under the deck edge), bootTop (band at
 * the waterline), hospital (green band + red crosses), funnelBands (black
 * whistle bands, as fraction of funnel height), funnelBandColors (stripes
 * under the black top), dummyFunnels (indices that never smoked).
 *
 * Warship fields:
 *   turrets     [{ along, count, size, superfire?, raise?, facing?, barrel?, z? }] — main
 *               battery bow → stern. along 0 = bow, 1 = stern; count = barrels;
 *               size = gunhouse width; superfire raises it over its neighbour;
 *               raise overrides barbette height above the supporting deck;
 *               facing "fore" | "aft" (default by position); z = fraction of
 *               the half-beam off the centreline.
 *   secondary   { along: [...], count, size } — mounts in port/starboard pairs.
 *   torpedoes   [{ along, tubes }] — centreline launchers.
 *   deckGun     { along, size } — submarine deck gun.
 *   protection  0..1 armour belt / torpedo bulge; shrinks side breaches.
 *   strength    hull girder factor; scales the break-up thresholds (liner = 1).
 *   reserveBuoyancy  flood fraction absorbed before she settles (default 0.38).
 *   screws      propeller count.
 *   measure22   USN Measure 22 navy-blue band up to the lowest deck line.
 *   antifoulColor  paint below the waterline; deck "teak" | "steel", deckColor.
 */

const USN_HAZE = 0x7b8288;
const USN_NAVY_BLUE = 0x3d4a58;
const USN_DECK_BLUE = 0x4c5764;
const RN_GREY = 0x767d82;
const RN_LIGHT = 0x8b9195;
const KM_GREY = 0x8e9497;
const IJN_GREY = 0x697070;
const RM_GREY = 0x9aa1a3;
const MN_GREY = 0x8b969c;
const VMF_GREY = 0x7a847f;
const BLACK_BOOT = 0x1c1d1f;

const LINERS = [
  {
    id: "titanic",
    name: "RMS Titanic",
    year: 1912,
    category: "liner",
    navy: "Merchant",
    length: 26.9,
    beam: 2.85,
    height: 2.65,
    draft: 1.05,
    funnels: 4,
    funnelColor: 0xc8913f,
    dummyFunnels: [3],
    hullColor: 0x14161a,
    sheerLine: 0xc9a23a,
    superstructureColor: 0xf0ebe3,
    compartments: 6,
    notes: "Olympic-class — long, four buff funnels (the fourth a dummy)",
  },
  {
    id: "britannic",
    name: "HMHS Britannic",
    year: 1914,
    category: "liner",
    navy: "Merchant",
    length: 27.2,
    beam: 2.95,
    height: 2.75,
    draft: 1.08,
    funnels: 4,
    funnelColor: 0xc8913f,
    dummyFunnels: [3],
    hullColor: 0xefebe3,
    hospital: { band: 0x2f7a3c, cross: 0xb8232a },
    superstructureColor: 0xf4efe8,
    compartments: 6,
    notes: "Olympic sister in hospital-ship white, green band and red crosses",
  },
  {
    id: "nomadic",
    name: "SS Nomadic",
    year: 1911,
    category: "liner",
    navy: "Merchant",
    length: 6.7,
    beam: 1.45,
    height: 1.55,
    draft: 0.52,
    funnels: 1,
    funnelColor: 0xc8913f,
    hullColor: 0x15171b,
    sheerLine: 0xc9a23a,
    superstructureColor: 0xf7f2ea,
    compartments: 3,
    notes: "Titanic's tender — compact ferry hull",
  },
  {
    id: "queen-elizabeth",
    name: "RMS Queen Elizabeth",
    year: 1940,
    category: "liner",
    navy: "Merchant",
    length: 31.4,
    beam: 3.65,
    height: 3.25,
    draft: 1.22,
    funnels: 2,
    funnelColor: 0xc0461f,
    funnelBands: [0.62, 0.72],
    hullColor: 0x111317,
    bootTop: 0xe8e4dc,
    superstructureColor: 0xf8f4ed,
    compartments: 7,
    notes: "Cunard giant — beamy, two tall red funnels",
  },
  {
    id: "lusitania",
    name: "RMS Lusitania",
    year: 1906,
    category: "liner",
    navy: "Merchant",
    length: 24.0,
    beam: 2.72,
    height: 2.55,
    draft: 1.0,
    funnels: 4,
    funnelColor: 0xc0461f,
    funnelBands: [0.58, 0.7],
    hullColor: 0x131519,
    superstructureColor: 0xf0eae2,
    compartments: 5,
    notes: "Four-funnel Cunarder, fine bow",
  },
  {
    id: "andrea-doria",
    name: "SS Andrea Doria",
    year: 1951,
    category: "liner",
    navy: "Merchant",
    length: 21.3,
    beam: 2.8,
    height: 2.85,
    draft: 0.95,
    funnels: 1,
    funnelColor: 0xf0ebe2,
    funnelBandColors: [0x2f7a3c, 0xf0ebe2, 0xb8232a],
    hullColor: 0x121418,
    bootTop: 0xe8e4dc,
    superstructureColor: 0xfaf6f0,
    compartments: 5,
    notes: "Post-war Italian liner — sleek, single funnel",
  },
  {
    id: "empress",
    name: "RMS Empress of Ireland",
    year: 1906,
    category: "liner",
    navy: "Merchant",
    length: 17.4,
    beam: 2.25,
    height: 2.25,
    draft: 0.88,
    funnels: 2,
    funnelColor: 0xcfa24a,
    hullColor: 0x14161a,
    superstructureColor: 0xeee8e0,
    compartments: 4,
    notes: "Canadian Pacific — shorter, two funnels",
  },
];


const WARSHIPS = [
  // --- United States Navy ---
  {
    id: "iowa",
    name: "USS Iowa (BB-61)",
    year: 1943,
    category: "battleship",
    navy: "USN",
    length: 27.0,
    beam: 3.3,
    height: 2.1,
    draft: 1.1,
    funnels: 2,
    funnelColor: USN_HAZE,
    hullColor: USN_HAZE,
    measure22: USN_NAVY_BLUE,
    superstructureColor: USN_HAZE,
    deckColor: USN_DECK_BLUE,
    compartments: 8,
    screws: 4,
    protection: 0.6,
    strength: 1.35,
    turrets: [
      { along: 0.215, count: 3, size: 1.25 },
      { along: 0.29, count: 3, size: 1.25, superfire: true },
      { along: 0.765, count: 3, size: 1.25 },
    ],
    secondary: { along: [0.37, 0.43, 0.49, 0.55, 0.61], count: 2, size: 0.48 },
    notes: "Fast battleship — nine 16-inch guns, Measure 22 camouflage",
  },
  {
    id: "essex",
    name: "USS Essex (CV-9)",
    year: 1942,
    category: "carrier",
    navy: "USN",
    length: 26.7,
    beam: 2.8,
    height: 2.3,
    draft: 0.87,
    funnels: 1,
    funnelColor: USN_NAVY_BLUE,
    hullColor: USN_NAVY_BLUE,
    superstructureColor: USN_NAVY_BLUE,
    deckColor: USN_DECK_BLUE,
    compartments: 8,
    screws: 4,
    protection: 0.25,
    strength: 1.15,
    turrets: [
      { along: 0.3, count: 2, size: 0.5, z: 0.72 },
      { along: 0.35, count: 2, size: 0.5, z: 0.72, facing: "fore" },
      { along: 0.61, count: 2, size: 0.5, z: 0.72, facing: "aft" },
      { along: 0.66, count: 2, size: 0.5, z: 0.72 },
    ],
    notes: "Fleet carrier in Measure 21 navy blue — island and funnel to starboard",
  },
  {
    id: "fletcher",
    name: "USS Fletcher (DD-445)",
    year: 1942,
    category: "destroyer",
    navy: "USN",
    length: 11.5,
    beam: 1.2,
    height: 1.35,
    draft: 0.55,
    funnels: 2,
    funnelColor: USN_HAZE,
    hullColor: USN_HAZE,
    measure22: USN_NAVY_BLUE,
    superstructureColor: USN_HAZE,
    deck: "steel",
    deckColor: USN_DECK_BLUE,
    compartments: 5,
    screws: 2,
    strength: 0.85,
    turrets: [
      { along: 0.17, count: 1, size: 0.42 },
      { along: 0.24, count: 1, size: 0.42, superfire: true },
      { along: 0.66, count: 1, size: 0.42, facing: "aft" },
      { along: 0.77, count: 1, size: 0.42, superfire: true },
      { along: 0.88, count: 1, size: 0.42 },
    ],
    torpedoes: [
      { along: 0.46, tubes: 5 },
      { along: 0.575, tubes: 5 },
    ],
    notes: "Flush-deck destroyer — five single 5-inch mounts, two quintuple tube banks",
  },
  {
    id: "gato",
    name: "USS Gato (SS-212)",
    year: 1941,
    category: "submarine",
    navy: "USN",
    length: 9.5,
    beam: 0.83,
    height: 0.5,
    draft: 0.52,
    funnels: 0,
    funnelColor: 0x1d2023,
    hullColor: 0x1d2023,
    antifoulColor: 0x18191b,
    superstructureColor: 0x25282b,
    deck: "teak",
    compartments: 6,
    screws: 2,
    strength: 1.4,
    reserveBuoyancy: 0.16,
    deckGun: { along: 0.57, size: 0.26 },
    notes: "Fleet boat in Measure 9 black — long casing, periscope shears",
  },

  // --- Royal Navy ---
  {
    id: "king-george-v",
    name: "HMS King George V (41)",
    year: 1940,
    category: "battleship",
    navy: "RN",
    length: 22.7,
    beam: 3.14,
    height: 2.35,
    draft: 1.0,
    funnels: 2,
    funnelColor: RN_GREY,
    hullColor: RN_GREY,
    bootTop: BLACK_BOOT,
    superstructureColor: RN_LIGHT,
    compartments: 8,
    screws: 4,
    protection: 0.65,
    strength: 1.35,
    turrets: [
      { along: 0.2, count: 4, size: 1.35 },
      { along: 0.285, count: 2, size: 1.05, superfire: true },
      { along: 0.79, count: 4, size: 1.35 },
    ],
    secondary: { along: [0.36, 0.43, 0.6, 0.67], count: 2, size: 0.55 },
    notes: "Quadruple and twin 14-inch turrets, square box bridge",
  },
  {
    id: "hood",
    name: "HMS Hood (51)",
    year: 1920,
    category: "battleship",
    navy: "RN",
    length: 26.2,
    beam: 3.2,
    height: 2.2,
    draft: 0.98,
    funnels: 2,
    funnelColor: RN_LIGHT,
    hullColor: RN_LIGHT,
    bootTop: BLACK_BOOT,
    superstructureColor: RN_LIGHT,
    compartments: 8,
    screws: 4,
    protection: 0.4,
    strength: 1.05,
    turrets: [
      { along: 0.19, count: 2, size: 1.05 },
      { along: 0.26, count: 2, size: 1.05, superfire: true },
      { along: 0.76, count: 2, size: 1.05, superfire: true },
      { along: 0.83, count: 2, size: 1.05 },
    ],
    secondary: { along: [0.58, 0.64], count: 2, size: 0.4 },
    notes: "Battlecruiser — long, sleek, the Mighty Hood",
  },
  {
    id: "ark-royal",
    name: "HMS Ark Royal (91)",
    year: 1938,
    category: "carrier",
    navy: "RN",
    length: 24.3,
    beam: 2.89,
    height: 2.4,
    draft: 0.85,
    funnels: 1,
    funnelColor: RN_GREY,
    hullColor: RN_GREY,
    bootTop: BLACK_BOOT,
    superstructureColor: RN_LIGHT,
    deck: "steel",
    deckColor: 0x6e7478,
    compartments: 8,
    screws: 3,
    protection: 0.25,
    strength: 1.1,
    turrets: [
      { along: 0.1, count: 2, size: 0.42, z: 0.86 },
      { along: 0.1, count: 2, size: 0.42, z: -0.86 },
      { along: 0.84, count: 2, size: 0.42, z: 0.86, facing: "aft" },
      { along: 0.84, count: 2, size: 0.42, z: -0.86, facing: "aft" },
    ],
    notes: "Enclosed hurricane bow and double hangar — flight deck almost to the stem",
  },
  {
    id: "cossack",
    name: "HMS Cossack (F03)",
    year: 1938,
    category: "destroyer",
    navy: "RN",
    length: 11.5,
    beam: 1.11,
    height: 1.3,
    draft: 0.4,
    funnels: 2,
    funnelColor: 0x5e6468,
    hullColor: 0x5e6468,
    superstructureColor: 0x6f767b,
    deck: "steel",
    deckColor: 0x585d61,
    compartments: 5,
    screws: 2,
    strength: 0.85,
    turrets: [
      { along: 0.16, count: 2, size: 0.5 },
      { along: 0.23, count: 2, size: 0.5, superfire: true },
      { along: 0.73, count: 2, size: 0.5, superfire: true },
      { along: 0.84, count: 2, size: 0.5 },
    ],
    torpedoes: [{ along: 0.62, tubes: 4 }],
    notes: "Tribal-class destroyer — raised forecastle, four twin 4.7-inch mounts",
  },

  // --- Kriegsmarine ---
  {
    id: "bismarck",
    name: "Bismarck",
    year: 1941,
    category: "battleship",
    navy: "KM",
    length: 25.1,
    beam: 3.6,
    height: 2.45,
    draft: 0.93,
    funnels: 1,
    funnelColor: KM_GREY,
    hullColor: KM_GREY,
    bootTop: BLACK_BOOT,
    superstructureColor: 0x9ba1a3,
    compartments: 8,
    screws: 3,
    protection: 0.7,
    strength: 1.35,
    turrets: [
      { along: 0.2, count: 2, size: 1.15 },
      { along: 0.27, count: 2, size: 1.15, superfire: true },
      { along: 0.73, count: 2, size: 1.15, superfire: true },
      { along: 0.8, count: 2, size: 1.15 },
    ],
    secondary: { along: [0.38, 0.47, 0.6], count: 2, size: 0.62 },
    notes: "Anton, Bruno, Caesar, Dora — Atlantic bow, one big capped funnel",
  },
  {
    id: "prinz-eugen",
    name: "Prinz Eugen",
    year: 1940,
    category: "cruiser",
    navy: "KM",
    length: 21.2,
    beam: 2.17,
    height: 2.05,
    draft: 0.72,
    funnels: 1,
    funnelColor: KM_GREY,
    hullColor: KM_GREY,
    bootTop: BLACK_BOOT,
    superstructureColor: 0x9ba1a3,
    compartments: 7,
    screws: 3,
    protection: 0.3,
    strength: 1.1,
    turrets: [
      { along: 0.19, count: 2, size: 0.78 },
      { along: 0.255, count: 2, size: 0.78, superfire: true },
      { along: 0.745, count: 2, size: 0.78, superfire: true },
      { along: 0.81, count: 2, size: 0.78 },
    ],
    notes: "Admiral Hipper-class heavy cruiser — clipper bow, tower bridge",
  },
  {
    id: "u-boat",
    name: "U-96 (Type VIIC)",
    year: 1940,
    category: "submarine",
    navy: "KM",
    length: 6.7,
    beam: 0.62,
    height: 0.42,
    draft: 0.47,
    funnels: 0,
    funnelColor: 0x858b8d,
    hullColor: 0x858b8d,
    antifoulColor: 0x2e3133,
    superstructureColor: 0x8d9395,
    deck: "teak",
    compartments: 5,
    screws: 2,
    strength: 1.4,
    reserveBuoyancy: 0.15,
    deckGun: { along: 0.33, size: 0.22 },
    notes: "Type VII U-boat — low saddle-tank hull, 88 mm deck gun, Wintergarten",
  },

  // --- Regia Marina ---
  {
    id: "littorio",
    name: "Littorio",
    year: 1940,
    category: "battleship",
    navy: "RM",
    length: 23.8,
    beam: 3.29,
    height: 2.35,
    draft: 0.96,
    funnels: 2,
    funnelColor: RM_GREY,
    hullColor: RM_GREY,
    superstructureColor: 0xa4aaac,
    compartments: 8,
    screws: 4,
    protection: 0.65,
    strength: 1.3,
    turrets: [
      { along: 0.2, count: 3, size: 1.2 },
      { along: 0.275, count: 3, size: 1.2, superfire: true },
      { along: 0.775, count: 3, size: 1.2 },
    ],
    secondary: { along: [0.37, 0.62], count: 3, size: 0.7 },
    notes: "Triple 15-inch turrets, elegant sheer, Pugliese torpedo defence",
  },
  {
    id: "zara",
    name: "Zara",
    year: 1931,
    category: "cruiser",
    navy: "RM",
    length: 18.3,
    beam: 2.06,
    height: 1.95,
    draft: 0.72,
    funnels: 2,
    funnelColor: RM_GREY,
    hullColor: RM_GREY,
    superstructureColor: 0xa4aaac,
    compartments: 7,
    screws: 2,
    protection: 0.35,
    strength: 1.1,
    turrets: [
      { along: 0.17, count: 2, size: 0.78 },
      { along: 0.235, count: 2, size: 0.78, superfire: true },
      { along: 0.755, count: 2, size: 0.78, superfire: true },
      { along: 0.825, count: 2, size: 0.78 },
    ],
    notes: "Heavy cruiser — long forecastle, two funnels",
  },

  // --- Imperial Japanese Navy ---
  {
    id: "yamato",
    name: "Yamato",
    year: 1941,
    category: "battleship",
    navy: "IJN",
    length: 26.3,
    beam: 3.89,
    height: 2.8,
    draft: 1.1,
    funnels: 1,
    funnelColor: IJN_GREY,
    hullColor: IJN_GREY,
    superstructureColor: 0x737a7a,
    compartments: 8,
    screws: 4,
    protection: 0.75,
    strength: 1.4,
    turrets: [
      { along: 0.235, count: 3, size: 1.55, barrel: 1.75 },
      { along: 0.31, count: 3, size: 1.55, barrel: 1.75, superfire: true },
      { along: 0.37, count: 3, size: 0.85, superfire: true, raise: 0.78 },
      { along: 0.73, count: 3, size: 0.85, superfire: true, raise: 0.18 },
      { along: 0.8, count: 3, size: 1.55, barrel: 1.75 },
    ],
    secondary: { along: [0.4, 0.46, 0.55, 0.6], count: 2, size: 0.42 },
    notes: "The largest battleship — 18.1-inch guns, raked funnel, pagoda tower",
  },
  {
    id: "akagi",
    name: "Akagi",
    year: 1938,
    category: "carrier",
    navy: "IJN",
    length: 26.1,
    beam: 3.13,
    height: 2.3,
    draft: 0.87,
    funnels: 1,
    funnelColor: 0x3a3c3d,
    hullColor: IJN_GREY,
    superstructureColor: 0x737a7a,
    deckColor: 0xb89468,
    compartments: 8,
    screws: 4,
    protection: 0.3,
    strength: 1.1,
    notes: "Converted battlecruiser — island to port, downturned stack to starboard",
  },
  {
    id: "fubuki",
    name: "Fubuki",
    year: 1928,
    category: "destroyer",
    navy: "IJN",
    length: 11.8,
    beam: 1.04,
    height: 1.25,
    draft: 0.32,
    funnels: 2,
    funnelColor: IJN_GREY,
    hullColor: IJN_GREY,
    superstructureColor: 0x737a7a,
    deck: "steel",
    deckColor: 0x6b4a36,
    compartments: 5,
    screws: 2,
    strength: 0.8,
    turrets: [
      { along: 0.15, count: 2, size: 0.48 },
      { along: 0.7, count: 2, size: 0.48, superfire: true, facing: "aft" },
      { along: 0.82, count: 2, size: 0.48 },
    ],
    torpedoes: [
      { along: 0.4, tubes: 3 },
      { along: 0.56, tubes: 3 },
      { along: 0.63, tubes: 3 },
    ],
    notes: "Special Type destroyer — high forecastle, enclosed gunhouses",
  },
  {
    id: "i-15",
    name: "I-15 (Type B1)",
    year: 1940,
    category: "submarine",
    navy: "IJN",
    length: 10.9,
    beam: 0.93,
    height: 0.6,
    draft: 0.51,
    funnels: 0,
    funnelColor: 0x222527,
    hullColor: 0x222527,
    antifoulColor: 0x1a1b1c,
    superstructureColor: 0x2a2d30,
    deck: "steel",
    deckColor: 0x3a3d40,
    compartments: 6,
    screws: 2,
    strength: 1.4,
    reserveBuoyancy: 0.17,
    deckGun: { along: 0.58, size: 0.3 },
    notes: "Aircraft-carrying submarine — hangar and catapult forward of the tower",
  },

  // --- Marine Nationale ---
  {
    id: "richelieu",
    name: "Richelieu",
    year: 1940,
    category: "battleship",
    navy: "MN",
    length: 24.8,
    beam: 3.31,
    height: 2.35,
    draft: 0.96,
    funnels: 1,
    funnelColor: MN_GREY,
    hullColor: MN_GREY,
    superstructureColor: 0x97a1a6,
    compartments: 8,
    screws: 4,
    protection: 0.65,
    strength: 1.3,
    turrets: [
      { along: 0.19, count: 4, size: 1.45 },
      { along: 0.275, count: 4, size: 1.45, superfire: true },
      { along: 0.79, count: 3, size: 0.68, superfire: true },
    ],
    secondary: { along: [0.71], count: 3, size: 0.68 },
    notes: "All-forward quadruple 15-inch turrets, tower and raked mack",
  },
  {
    id: "dunkerque",
    name: "Dunkerque",
    year: 1937,
    category: "battleship",
    navy: "MN",
    length: 21.5,
    beam: 3.11,
    height: 2.3,
    draft: 0.87,
    funnels: 1,
    funnelColor: MN_GREY,
    hullColor: MN_GREY,
    superstructureColor: 0x97a1a6,
    compartments: 8,
    screws: 4,
    protection: 0.5,
    strength: 1.2,
    turrets: [
      { along: 0.2, count: 4, size: 1.25 },
      { along: 0.285, count: 4, size: 1.25, superfire: true },
      { along: 0.8, count: 4, size: 0.6, superfire: true },
    ],
    secondary: { along: [0.73], count: 4, size: 0.55 },
    notes: "Fast battleship — forward-weighted quadruple 13-inch turrets",
  },

  // --- Soviet Navy ---
  {
    id: "kirov",
    name: "Kirov",
    year: 1938,
    category: "cruiser",
    navy: "VMF",
    length: 19.1,
    beam: 1.77,
    height: 1.75,
    draft: 0.63,
    funnels: 1,
    funnelColor: VMF_GREY,
    hullColor: VMF_GREY,
    superstructureColor: 0x87918c,
    compartments: 7,
    screws: 2,
    protection: 0.2,
    strength: 1.0,
    turrets: [
      { along: 0.19, count: 3, size: 0.85 },
      { along: 0.26, count: 3, size: 0.85, superfire: true },
      { along: 0.77, count: 3, size: 0.85 },
    ],
    torpedoes: [{ along: 0.6, tubes: 3 }],
    notes: "Light cruiser — triple 180 mm turrets, tripod foremast",
  },
];

export const SHIPS = [...LINERS, ...WARSHIPS];

/** Ship picker groups, in display order. */
export const CATEGORIES = [
  { id: "liner", label: "Ocean liners" },
  { id: "battleship", label: "Battleships" },
  { id: "cruiser", label: "Cruisers" },
  { id: "destroyer", label: "Destroyers" },
  { id: "carrier", label: "Aircraft carriers" },
  { id: "submarine", label: "Submarines" },
];

export const NAVIES = {
  Merchant: "Merchant",
  USN: "US Navy",
  RN: "Royal Navy",
  KM: "Kriegsmarine",
  RM: "Regia Marina",
  IJN: "Imperial Japanese Navy",
  MN: "Marine Nationale",
  VMF: "Soviet Navy",
};

/** Picker groups: each category's ships, grouped by navy in roster order. */
export function shipGroups(ships = SHIPS) {
  const order = Object.keys(NAVIES);
  return CATEGORIES.map((c) => ({
    ...c,
    ships: ships
      .filter((s) => s.category === c.id)
      .sort((a, b) => order.indexOf(a.navy) - order.indexOf(b.navy)),
  })).filter((g) => g.ships.length);
}

export function shipLabel(ship) {
  if (ship.category === "liner") return `${ship.name} (${ship.year})`;
  return `${ship.name} · ${NAVIES[ship.navy] ?? ship.navy} (${ship.year})`;
}

export function getShip(id) {
  return SHIPS.find((s) => s.id === id) ?? SHIPS[0];
}
